apiVersion: apps/v1
kind: Deployment
metadata:
  name: fingerprint
  labels:
    app: fingerprint
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fingerprint
  template:
    metadata:
      labels:
        app: fingerprint
    spec:
      containers:
        - name: fingerprint
          image: acrjlgc17.azurecr.io/fingerprint
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      imagePullSecrets:
        - name: regcred
---
#############################
#############################
kind: Service
apiVersion: v1
metadata:
  name: fingerprint
spec:
  selector:
    app: fingerprint
  ports:
    - port: 9001
      targetPort: 9001
  type: LoadBalancer